language: go

services:
  - docker

# TODO: Add Travis DOCKER_PASSWORD encrypted secret.

branches:
  only:
  - master

before_install:
  - if [ ! -z \"$DOCKER_USERNAME\" ]; then docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD || true; fi

script:
  - make build

deploy:
  - provider: script
    script: make push-image
    on:
      tags: true
      condition: ${DOCKER_USERNAME} && ${DOCKER_PASSWORD}
  - provider: script
    script: make push-image
    on:
      branch: master
      condition: ${DOCKER_USERNAME} && ${DOCKER_PASSWORD}
