variables:
  - name: name1
    value: value1
  - name: name2
    value: value2
triggers:
  - when: triggercond0
    action:
      applyResources:
        directory: dir1
  - when: triggercond1
    triggers:
      - when: triggercond2
        trigger:
          - when: triggercond3
            action:
              applyResources:
                directory: dir2