variables:
  - name: kubeNamespace
    value: ' "kabanero" '
  - name: serviceAccount
    value: ' "appsody-sa" '
  - name: registry
    value: ' "docker-registry.default.svc:5000/" + kubeNamespace +  "/" + event.repository.name '
triggers:
  - when: 'has(collectionID)' # appsody build
    triggers:
       - when:  'repositoryEvent == "push"'  # push can be push code or tag
         triggers:
             - when:  'refs[1] == "heads" && refs[2] == "master"' # push to master
               action:
                   applyResources:
                     directory: pushMaster
