variables:
  - name: kubeNamespace
    value: ' "kabanero" '
  - name: serviceAccount
    value: ' "appsody-sa" '
  - name: registry
    value: ' "docker-registry.default.svc:5000/" + kubeNamespace +  "/" + event.repository.name '
  - when: 'kabanero.eventType=="Repository"'
    name: kubeNameSuffix
    value: 'event.repository.owner.login + "-" + event.repository.name + "-" + kabanero.jobid'
triggers:
  - when: 'has(kabanero.collectionID)' # appsody build
    triggers:
       - when:  'kabanero.repositoryEvent == "push"'  # push can be push code or tag
         triggers:
             - when:  'kabanero.ref[1] == "heads" && kabanero.ref[2] == "master"' # push to master
               action:
                   applyResources:
                     directory: pushMaster
