apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name:  {{.kubeNameSuffix}}
  namespace: {{.kubeNamespace}}
spec:
  pipelineRef:
    name: {{.kabanero.collectionID}}-build-deploy-pipeline
  resources:
  - name: git-source
    resourceRef:
      name: git-{{.kubeNameSuffix}}
  - name: docker-image
    resourceRef:
      name: docker-{{.kubeNameSuffix}}
  serviceAccount: {{.serviceAccount}}
  timeout: 1h0m0s
